#!/bin/bash
clear
TASK_START=$(date +%s.%N)

./gradlew clean build -Dkotlin.warnings.as.errors=true -x test -x detekt -x distZip -x distTar -x bootDistZip -x bootDistTar --warning-mode all

LINE="################################################################################################################"
S1="\x1B[32m"
S2="\x1B[0m"
NC="\033[0m"

TASK_EXEC_TIME=$(echo "$(date +%s.%N) - $TASK_START" | bc -l)
