#!/bin/bash
clear
TASK_START=$(date +%s.%N)

LINE="################################################################################################################"
S1="\x1B[32m"
S2="\x1B[0m"
NC="\033[0m"

echo -e "$S1$LINE$2"

echo -e "check for library updates ..."

gradle dependencyUpdates

TASK_EXEC_TIME=$(echo "$(date +%s.%N) - $TASK_START" | bc -l)

echo -e "$S1$LINE$2"
echo -e "$S1 successfully finished in $TASK_EXEC_TIME second(s) at $(date) $S2"
echo -e "$S1$LINE$2"
echo -e "$NC "
