kotlinLanguageVersion=2.1.0
kapt.use.k2=true
kotlin.code.style=official
#kotlin.incremental.useClasspathSnapshot=true
kotlin.build.report.output=file
kotlin.build.internal.gradle.setup=true
kotlin.jvm.target.validation.mode=error
kotlin.options.suppressFreeCompilerArgsModificationWarning=true
org.gradle.jvmargs=-Xmx3072m -XX:+UseParallelGC -Dfile.encoding=UTF-8 -Duser.country=US -Dorg.gradle.internal.publish.checksums.insecure=true
org.gradle.vfs.watch=true
org.gradle.vfs.verbose=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.console=auto
org.gradle.daemon.performance.enable-monitoring=false
#org.gradle.caching.debug=true
#org.gradle.debug=false
#org.gradle.configuration-cache=true
org.gradle.logging.level=warn
org.gradle.warning.mode=summary
org.gradle.workers.max=24
org.gradle.configureondemand=true
#---------------------------------------------------
systemProp.file.encoding=UTF-8
systemProp.user.country=US
systemProp.org.gradle.internal.publish.checksums.insecure=true
