syntax = "proto3";

package projectClient;
import "google/protobuf/wrappers.proto";
import "project-dto.proto";

option java_package = "org.dbs.tree.client";
option java_multiple_files = true;

service ProjectService {
  // User
  rpc createOrUpdateProject (CreateOrUpdateProjectRequest) returns (CreateOrUpdateProjectResponse) {}
  //rpc getUserCredentials (UserCredentialsRequest) returns (UserCredentialsResponse) {}
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
