---
debug: false
trace: off
server:
  port: 7443
  ssl:
    enabled: true
    key-store: classpath:k11dev.tech.jks
    key-store-password: 123123
    key-store-type: jks
  servlet:
    context-path: /
    session:
      timeout: 60
grpc:
  server:
    port: 17443
    security:
      enabled: true
      certificateChain: classpath:k11dev.tech.pem
      privateKey: classpath:k11dev.tech.key
spring:
  profiles:
    active: default
  main:
    lazy-initialization: true
    web-application-type: reactive
    banner-mode: console
  jmx:
    enabled: false
  web:
    locale: en_CA
    locale-resolver: fixed
  security:
    user:
      name: user
      password: 123123
  r2dbc:
    username: dev_sandbox_admin
    password: b81ad53345de4a1a8583168f1
    url: r2dbc:postgresql://dev01.k11dev.tech:5432/dev_sandbox_db
    pool:
      enabled: true
      initial-size: 2
      max-size: 10
      validation-query: SELECT 1
      max-life-time: 7200000
      max-idle-time: 12000000
    next-val-cmd: SELECT nextval('seq_action_id')
    repositories:
      enabled: true
  application:
    name: cc-sandbox
  jackson:
    serialization:
      fail-on-empty-beans: false
  data:
    redis:
      repositories:
        enabled: true
      host: 127.0.0.1
      port: 6379
      timeout: 2000
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  cache:
    redis:
      time-to-live: 86400
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600
    use-code-as-default-message: true
    fallback-to-system-locale: true
  codec:
    max-in-memory-size: 20MB
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093
    listener:
      type: batch
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
      properties:
        isolation.level: read_committed
logging:
  register-shutdown-hook: false
  level:
    root: WARN
    org.dbs: DEBUG
    org.springframework: WARN
    org.springframework.boot: WARN
  config: classpath:log4j2.xml
network:
  cors:
    allowed-path: localhost
    allowed-origins:
      additional: localhost
    allowed-headers: "*"
    allowed-methods: "*"
    allowed-credentials: false
    max-age: 1
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        #include: "metrics, health, prometheus"
        #exclude: "beans"
  health:
    redis:
      enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: false
  swagger-ui:
    use-root-path: true
    enabled: false
    operationsSorter: method
    disable-swagger-default-url: true
  cache:
    disabled: true
config:
  grpc:
    reflection:
      enabled: false
  liveness:
    hosts: { #'media-dev.k11dev.tech':9000,
      #                'admin.k11dev.tech':443,
      'google.com': 443,
      'uonmap.com': 443 }
  restful:
    return-error-2-response: true
    profile:
      name: ${spring.application.name}
    security:
      google:
        server:
          host-port: https://google.com
          recaptcha:
            v3:
              site: 6LdIcqcpAAAAAFGLJd5OIVIgUb-ujHrWud8Mphyo
              #secret: 6Lc1AowpAAAAAJLdoT_YdWHN2kAeTK9LTWvX6hoO
              secret: 6LemAowpAAAAANJUhJpr5pzufc_vZCNywewt63DJ
              routes:
                siteverify: /recaptcha/api/siteverify
  entity:
    core:
      action:
        execution:
          async-alg-store:
            enabled: false
            delay: 50
  cache:
    jedis:
      enabled: true
  references:
    auto-synchronize: true
    privilege-group: false
    privilege: false
  security:
    security-routes:
      enabled: false
    profile:
      name: advanced
      advanced-white-uri-list: /info,/health
    jwt:
      name: standard
      secret-key: ThisIsSecretForJWTHS512ThisIsSecretForJWTHS512
    bucket4j:
      enabled: false
      trusted-ips: localhost
---
spring:
  config:
    activate:
      on-profile: k9-test
debug: false
trace: off
server:
  ssl:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: k11-dev-ssl-on
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
grpc:
  server:
    port: 17443
config:
  references:
    auto-synchronize: true
  grpc:
    reflection:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: ilona-test
  data:
    redis:
      host: localhost
      port: 6379
  r2dbc:
    username: dev_mgmt_admin
    password: 366a5a233598442398448705e
    url: r2dbc:postgresql://localhost/dev_mgmt_db
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
config:
  references:
    auto-synchronize: false
  grpc:
    reflection:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: h25-dev-ssl-on
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093
  data:
    redis:
      repositories:
        enabled: true
      host: media-dev.smartsafeschool.com
      port: 6379
      timeout: 2000
server:
  ssl:
    enabled: false
grpc:
  server:
    security:
      enabled: false
config:
  references:
    auto-synchronize: false
  grpc:
    reflection:
      enabled: true
