package org.dbs.validator

import org.dbs.enums.RefEnum

enum class Field(private val value: String, private val code: Int) : RefEnum {
    UNKNOWN_FIELD("UNKNOWN_FIELD", 1),
    FILE_NAME("FILE_NAME", 10),
    FILE_CONTENT("FILE_CONTENT", 11),
    FLD_MESSAGE("MESSAGE_FIELD", 20),
    FLD_SEARCH_MASK("SEARCH_MASK_FIELD", 21),
    FLD_CODE("CODE_FIELD", 30),
    FLD_HOST_ADDRESS("host.address", 50),
    FLD_ACCESS_JWT("sss.jwt.access", 60),
    FLD_REFRESH_JWT("sss.jwt.refresh", 61),
    SSS_JWT("sss.jwt", 62),
    CORE_ACTION1("field.general", 100),
    CORE_ACTION2("field1", 101),
    CORE_ACTION3("field2", 102),
    GENERAL_FIELD("fld.general", 1000),
    JWT_TOKEN("fld.jwt", 1001),
    JWT_TOKEN_CLAIM("fld.jwt.claim", 1002),
    COUNTRY("fld.country", 2000),
    CURRENCY("fld.currency", 3000),
    REGION("fld.region", 5000),
    FLD_ACCESS_TOKEN("common.access.token", 4000),  //Proxies
    ALG_ID("fld.algId", 100000), PROXY_ID("fld.proxyId", 100001),
    COUNTRY_ID("fld.countryId", 100002),
    PROXY_PROVIDER_ID("fld.proxyProviderId", 100003),
    ALG_UNKNOWN("usage.unknown", 200000),
    CREATION_DATE("CREATION_DATE", 100004),
    // Contracts
    CONTRACT_ID("cntr.contract_id", 300001),
    CONTRACT_DATE("cntr.contract_date", 300011),
    BEGIN_DATE("cntr.begin_date", 300012),
    END_DATE("cntr.end_date", 300013),
    SUBSCRIPTION_AMOUNT("cntr.subscription.amount", 300014),
    // Payments
    PAYMENT_DATE("pmt.pmt_date", 400001),
    PACKAGE("pmt.package", 400002),
    LOGIN_TOKEN("pmt.login_token", 400003),
    PLATFORM("platform", 400004),
    PAYMENT_SERVICE("pmt.service", 400005),
    PAYMENT_STATUS("pmt.status", 400006),
    PAYMENT_SUMM("pmt.summ", 400007),
    PAYMENT_SUMM_EQU("pmt.summ_equ", 400008),
    PAYMENT_CURRENCY("pmt.currency", 400009),
    APPLY_ORIGINAL_TRANSACTION_ID("ios.transaction.id", 400010),
    GOOGLE_PURCHASE_TOKEN("android.transaction.id", 400020),  // External Users
    EU_KIND_ID("external.user.user_kind_id", 500010),
    EU_ACCESS_TOKEN("external.user.number", 500020),
    // BPC
    BPC_MONTH("bpc.month", 500030),
    BPC_YEAR("bpc.year", 500040),
    // Common
    SSS_SORT_FIELD("sss.sort.field", 500050),
    SSS_SORT_ORDER("sss.sort.order", 500060),
    SSS_USER_ID("sss.user.id", 600000),
    SSS_USER_LOGIN("sss.user.login", 600001),
    SSS_USER_OLD_LOGIN("sss.user.old.login", 600002),
    SSS_USER_PASSWORD("sss.user.password", 600003),
    SSS_USER_EMAIL("sss.user.email", 600004),
    SSS_USER_ACCOUNT_V1("sss.user.account.v1.id", 600005),
    SSS_USER_ACCOUNT_BILL_V1("sss.user.account.bill.v1", 600006),
    SSS_USER_ACCOUNT_PAYMENT_V1("sss.user.account.payment.v1", 600007),
    SSS_USER_PHONE("sss.user.phone", 600011),
    SSS_LOGIN_USER("sss.login.user", 600012),
    SSS_LOGIN_USER_PWD("sss.login.user.password", 600013),
    SSS_LOGIN_APP_PACKAGE("cm.login.app.package", 600014),
    SSS_LOGIN_APP_VERSION("sss.login.app.version", 600015),
    SSS_USER_FIRST_NAME("sss.user.first.name", 600016),
    SSS_USER_LAST_NAME("sss.user.last.name", 600017),
    SSS_USER_MIDDLE_NAME("sss.user.middle.name", 600018),
    SSS_USER_STATUS("sss.user.status", 600019),
    SSS_ROLE("sss.role", 1000001),

    SSS_SCHOOL("sss.school", 1000005),
    SSS_SCHOOL_NAME("sss.school.name", 1000010),
    SSS_SCHOOL_STATUS("sss.school.status", 1000011),

    SSS_PARENT_SCHOOL("sss.school.parent", 1000006),
    SSS_ACCESS_TOKEN("sss.access.token", 1000007),
    SSS_ASSIGN_ROLE_ATTR("sss.assign.role.attr", 1000021),
    SSS_ASSIGN_ROLE_CODE("sss.assign.role.code", 1000022),
    SSS_ASSIGN_PRIVILEGE_ATTR("sss.assign.privilege.attr", 1000031),
    SSS_ASSIGN_PRIVILEGE_CODE("sss.assign.privilege.code", 1000032),
    SSS_VENDOR_ACCESS_TOKEN("sss.vendor.access.token", 1000100),
    SSS_VENDOR_LOGIN("sss.vendor.login", 1000101),
    SSS_VENDOR_ID("sss.vendor.id", 1000102),
    SSS_VENDOR_REGION("sss.vendor.regions", 1000103),
    SSS_VENDOR_COUNTRY("sss.vendor.country", 1000104),
    SSS_VENDOR_EMAIL("sss.vendor.email", 1000105),
    SSS_VENDOR_STATUS("sss.vendor.status", 1000106),
    SSS_VENDOR_FIRST_NAME("sss.vendor.first.name", 1000111),
    SSS_VENDOR_LAST_NAME("sss.vendor.last.name", 1000112),
    SSS_VENDOR_PASSWORD("sss.vendor.password", 1000113),
    SSS_VENDOR_OLD_PASSWORD("sss.vendor.password.old", 1000114),
    SSS_VENDOR_ADDRESS("sss.vendor.address", 1000115),
    SSS_VENDOR_CITY("sss.vendor.city", 1000116),
    SSS_VENDOR_PHONE("sss.vendor.phone", 1000117),
    SSS_VENDOR_FAX("sss.vendor.fax", 1000119),
    SSS_VENDOR_PUBLIC_NAME("sss.vendor.public.name", 1000120),
    SSS_VENDORS("sss.vendors", 1000130),
    SSS_ABSTRACT_PRODUCT_CODE("sss.abstract.product.code", 1001000),
    SSS_ABSTRACT_PRODUCT_SHORT_NAME("sss.abstract.product.short.name", 1001001),
    SSS_ABSTRACT_PRODUCT("sss.abstract.product", 10010015),
    SSS_ABSTRACT_PRODUCT_ID("sss.abstract.product.id", 10010016),
    SSS_ABSTRACT_PRODUCT_CATEGORY("sss.abstract.product.category", 1001003),
    SSS_ABSTRACT_PRODUCT_STATUS("sss.abstract.product.status", 1001004),
    SSS_ABSTRACT_PRODUCT_IS_NEW("sss.abstract.product.is.new", 10010011),
    SSS_ABSTRACT_PRODUCT_LIST("sss.abstract.product.list", 10010017),
    SSS_ABSTRACT_PRODUCT_BY_CAT("sss.abstract.product.by.category", 10010018),
    SSS_PRODUCT_ATTRIBUTE("sss.product.attribute", 1001013),
    SSS_PRODUCT_ATTRIBUTE_UNIT_NAME("sss.product.attribute.unit.name", 1001005),
    SSS_PRODUCT_ATTRIBUTE_UNIT_CODE("sss.product.attribute.unit.code", 1001006),
    SSS_PRODUCT_ATTRIBUTE_NAME("sss.product.attribute.name", 1001007),
    SSS_PRODUCT_ATTRIBUTE_CODE("sss.product.attribute.code", 1001008),
        SSS_PRODUCT_ATTRIBUTE_PRIORITY("sss.product.attribute.priority", 1001020),
    SSS_PRODUCT_ATTRIBUTE_ASSIGNED("sss.product.attribute.assign", 10010012),
    SSS_PRODUCT_ATTRIBUTE_IS_NUMERIC("sss.product.attribute.is.numeric", 10010013),
    SSS_PRODUCT_ATTRIBUTE_TYPE("sss.product.attribute.type", 1001009),
    SSS_PRODUCT_ATTRIBUTE_STATUS("sss.product.attribute.status", 1001010),
    SSS_PRODUCT_ATTRIBUTE_MEASURE("sss.product.attribute.measure", 1001015),
    SSS_ABSTRACT_PRODUCT2ATTRIBUTE("sss.abstract.product.2.attribute", 1001014),
    SSS_ABSTRACT_PRODUCT2ATTRIBUTE_PARAMS("sss.abstract.product.attribute.2.params", 1001011),
    SSS_ABSTRACT_PRODUCT2ATTRIBUTE_STATUS("sss.abstract.product.attribute.2.status", 1001012),
    SSS_CURRENCY_SKU("sss.currency.sku", 1002000),
    SSS_CURRENCY_AMOUNT("sss.currency.amount", 1002001),
    SSS_CURRENCY_QUANTITY("sss.currency.quantity", 1002002),
    SSS_PRODUCT_PRICE("sss.product.price", 1003000),
    SSS_PRODUCT_ACTUAL_DATE_FROM("sss.product.actual.date", 1004000),
    SSS_PRODUCT_PRICE_AMOUNT("sss.product.price.amount", 1005000),
    SSS_PRODUCT_PRICE_DATE("sss.product.price.date", 1005001),
    SSS_PRODUCT_PRICE_CURRENCY("sss.product.price.currency", 1005002),
    SSS_PRODUCT_PRICE_CURRENT("sss.product.price.current", 1005003),
    SSS_PRODUCT_PRICE_STATUS("sss.product.price.status", 1005004),
    SSS_OFFICE("sss.office", 1006100),
    SSS_OFFICE_CODE("sss.office.code", 1006101),
    SSS_PARENT_OFFICE_CODE("sss.office.parent.code", 1007102),
    SSS_OFFICE_COUNTRY("sss.office.country", 1007103),
    SSS_OFFICE_STATUS("sss.office.status", 1007104),
    SSS_OFFICE_NAME("sss.office.name", 1007105),
    SSS_OFFICE_ADDRESS("sss.office.address", 1007110),
    SSS_OFFICE_REGION("sss.office.region", 1007120),
    SSS_OFFICE_NOTE("sss.office.note", 1007130),
    SSS_DEPARTMENT("sss.department", 1008100),
    SSS_DEPARTMENT_CODE("sss.department.code", 1008101),
    SSS_DEPARTMENT_NAME("sss.department.name", 1008102),
    SSS_PARENT_DEPARTMENT_CODE("sss.department.parent.code", 1009102),
    SSS_DEPARTMENT_STATUS("sss.department.status", 1009103),
    SSS_DEPARTMENT_NOTE("sss.department.note", 1009110),
    SSS_POST("sss.post", 1011100),
    SSS_POST_CODE("sss.post.code", 1011101),
    SSS_POST_NAME("sss.post.name", 1011102),
    SSS_POST_STATUS("sss.post.status", 1011103),
    SSS_POST_NOTE("sss.post.note", 1011110),
    SSS_SERVICE_GROUP("sss.service.group", 1013100),
    SSS_SERVICE_GROUP_CODE("sss.service.group.code", 1013101),
    SSS_PARENT_SERVICE_GROUP_CODE("sss.service.group.parent.code", 1014102),
    SSS_SERVICE_GROUP_STATUS("sss.service.group.status", 1015103),
    SSS_ISSUE_POINT("sss.issue.point", 1016100),
    SSS_ISSUE_POINT_CODE("sss.issue.point.code", 1016101),
    SSS_ISSUE_POINT_STATUS("sss.issue.point.status", 1017102),
    SSS_CUSTOMER("sss.customer", 1018100),
    SSS_CUSTOMER_LOGIN("sss.customer.login", 1018101),
    SSS_CUSTOMER_PASSWORD("sss.customer.password", 1018102),
    SSS_CUSTOMER_ATTRIBUTE("sss.customer.attribute", 1018199),
    SSS_CUSTOMER_ACCESS_TOKEN("sss.customer.access.token", 1019101),
    SSS_CUSTOMER_CODE("sss.customer.code", 1019102),
    SSS_CUSTOMER_STATUS("sss.customer.status", 1019103),
    SSS_DELIVERY_POINT("sss.delivery.point", 1020100),
    SSS_DELIVERY_POINT_CODE("sss.delivery.point.code", 1020101),
    SSS_DELIVERY_POINT_STATUS("sss.delivery.point.status", 1020102),
    SSS_DELIVERY_POINT_NAME("sss.delivery.point.name", 1020103),
    SSS_DELIVERY_POINT_ADDRESS("sss.delivery.point.address", 1020104),
    SSS_DELIVERY_POINT_CITY("sss.delivery.point.city", 1020105),
    SSS_DELIVERY_POINT_BASE("sss.delivery.point.base", 1020106),
    SSS_DELIVERY_POINT_INDEX("sss.delivery.point.index", 1020107),
    SSS_DELIVERY_POINT_COUNTRY("sss.delivery.point.country", 1020108),
    SSS_DELIVERY_POINT_REGION("sss.delivery.point.region", 1020109),
    SSS_ORDER("sss.order", 1021100),
    SSS_ORDER_NUM("sss.order.num", 1021101),
    SSS_ORDER_STATUS("sss.order.status", 1021103),
    SSS_ORDER_KIND("sss.order.kind", 1021104),
    SSS_ORDER_CURRENCY("sss.order.currency", 1021105),
    SSS_ORDER_SUM("sss.order.sum", 1021106),
    SSS_ORDER_RECHARGE_SUM("sss.order.recharge.sum", 1021107),
    SSS_ORDER_DELIVERY_TIME("sss.order.delivery.time", 1021108),
    SSS_ORDER_ITEM_COLLECTION("sss.order.items.collection", 1021109),
    SSS_ORDER_NOTE("sss.order.note", 1021110),
    SSS_ORDER_CODE("sss.order.code", 1021111),
    SSS_ORDER_CONTACT_NAME("sss.order.contact.name", 1021112),
    SSS_ORDER_CONTACT_LASTNAME("sss.order.contact.lastname", 1021113),
    SSS_ORDER_CONTACT_EMAIL("sss.order.contact.email", 1021114),
    SSS_ORDER_CONTACT_PHONE("sss.order.contact.phone", 1021115),
    SSS_ORDER_CONTACT_PHONE_2("sss.order.contact.phone.2", 1021116),
    SSS_ORDER_TERM_DATE("sss.order.term.date", 1021117),
    SSS_ORDER_DATE("sss.order.date", 1021118),
    SSS_ORDER_PAYMENT_SYSTEM_CODE("sss.order.payment.system.code", 1021119),
    //==============================================================================================
    SSS_ORDER_ITEM("sss.order.item", 1021201),
    SSS_ORDER_ITEM_NUM("sss.order.item.num", 1021202),
    SSS_ORDER_ITEM_STATUS("sss.order.item.status", 1021203),
    SSS_ORDER_ITEM_CURRENCY("sss.order.item.currency", 1021204),
    SSS_ORDER_ITEM_SUM("sss.order.item.sum", 1021205),
    SSS_ORDER_ITEM_PRICE("sss.order.item.price.sum", 1021206),
    SSS_ORDER_ITEM_AMOUNT("sss.order.item.amount.sum", 1021207),
    SSS_ORDER_ITEM_DELIVERY_SUM("sss.order.item.delivery.sum", 1021208),
    SSS_ORDER_ITEM_RECHARGE_SUM("sss.order.item.recharge.sum", 1021209),
    SSS_ORDER_ITEM_RECHARGE_DATE("sss.order.item.recharge.date", 1021210),
    SSS_ORDER_ITEM_RECHARGE_REASON("sss.order.item.recharge.reason", 1021211),
    SSS_ORDER_ITEM_NOTE("sss.order.item.note", 1021220),
    //==============================================================================================
    SSS_VENDOR_ACCOUNT("sss.vendor.account", 1030100),
    SSS_VENDOR_ACCOUNT_CODE("sss.vendor.account.code", 1030101),
    SSS_VENDOR_ACCOUNT_STATUS("sss.vendor.account.status", 1030102),
    SSS_VENDOR_ACCOUNT_BANK_NAME("sss.vendor.account.bank.name", 1030110),
    SSS_VENDOR_ACCOUNT_BANK_ADDRESS("sss.vendor.account.bank.address", 1030120),
    SSS_VENDOR_ACCOUNT_BANK_ACCOUNT("sss.vendor.account.bank.account", 1030130),
    SSS_VENDOR_ACCOUNT_CURRENCY("sss.vendor.account.currency", 1030140),
    SSS_VENDOR_ACCOUNT_SWIFT("sss.vendor.account.swift", 1030150),
    SSS_VENDOR_ACCOUNT_BIC("sss.vendor.account.bic", 1030160),
    SSS_VENDOR_SUPERVISOR_EMAIL("sss.vendor.supervisor.email", 1030170),
    SSS_VENDOR_SUPERVISOR_PHONE("sss.vendor.supervisor.phone", 1030180),
    SSS_VENDOR_REFERRAL_CODE("sss.vendor.referral.code", 1030190),
    //==============================================================================================
    SSS_STORE_ACCOUNT("sss.store.account", 1030200),
    SSS_STORE_ACCOUNT_CODE("sss.store.account.code", 1030210),
    SSS_STORE_ACCOUNT_DATE("sss.store.account.date", 1030215),
    SSS_STORE_ACCOUNT_STATUS("sss.store.account.status", 1030220),
    SSS_STORE_ACCOUNT_BANK_NAME("sss.store.account.bank.name", 1030230),
    SSS_STORE_ACCOUNT_NAME("sss.store.account.name", 1030231),
    SSS_STORE_ACCOUNT_BANK_ADDRESS("sss.store.account.bank.address", 1030240),
    SSS_STORE_ACCOUNT_BANK_ACCOUNT("sss.store.account.bank.account", 1030250),
    SSS_STORE_ACCOUNT_CURRENCY("sss.store.account.currency", 1030260),
    SSS_STORE_ACCOUNT_SWIFT("sss.store.account.swift", 1030270),
    SSS_STORE_ACCOUNT_BIC("sss.store.account.bic", 1030280),
    SSS_STORE_ACCOUNT_TYPE("sss.store.account.type", 1030290),
    //==============================================================================================
    SSS_CUSTOMER_ACCOUNT("sss.customer.account", 1030300),
    SSS_CUSTOMER_ACCOUNT_CODE("sss.customer.account.code", 1030310),
    SSS_CUSTOMER_ACCOUNT_STATUS("sss.customer.account.status", 1030320),
    SSS_CUSTOMER_ACCOUNT_BANK_NAME("sss.customer.account.bank.name", 1030330),
    SSS_CUSTOMER_ACCOUNT_BANK_ADDRESS("sss.customer.account.bank.address", 1030340),
    SSS_CUSTOMER_ACCOUNT_BANK_ACCOUNT("sss.customer.account.bank.account", 1030350),
    SSS_CUSTOMER_ACCOUNT_CURRENCY("sss.customer.account.currency", 1030360),
    SSS_CUSTOMER_ACCOUNT_SWIFT("sss.customer.account.swift", 1030370),
    SSS_CUSTOMER_ACCOUNT_BIC("sss.customer.account.bic", 1030380),
    //==============================================================================================
    SSS_RECEIVER_ACCOUNT_BANK_ACCOUNT("sss.receiver.account.bank.account", 1030390),
    SSS_SUPPLIER_ACCOUNT_BANK_ACCOUNT("sss.supplier.account.bank.account", 1030391),
    B_ACCOUNT_BANK_ACCOUNT("b.account.bank.account", 1030392),
    //==============================================================================================
    B_CARD_NUM("b.card.num", 1040390),
    B_CARD_FIRST_NAME("b.card.first.name", 1040391),
    B_CARD_LAST_NAME("b.card.last.name", 1040392),
    B_CARD_CVV("b.card.cvv", 1040393),
    B_CARD_VALIDITY_PERIOD("b.card.validity.period", 1040394),
    //==============================================================================================
    SSS_SHIPMENT("sss.shipment", 1030400),
    SSS_SHIPMENT_CODE("sss.shipment.code", 1030410),
    SSS_SHIPMENT_SERVICE("sss.shipment.service", 1030420),
    SSS_SHIPMENT_TRACKER_NUMBER("sss.shipment.tracker.number", 1030430),
    SSS_SHIPMENT_TRACKER_WEBSITE("sss.shipment.tracker.website", 1030431),
    SSS_SHIPMENT_COMMENT("sss.shipment.comment", 1030440),
    SSS_SHIPMENT_DEPARTURE_DATE_TIME("sss.shipment.departure.date.time", 1030450),
    SSS_SHIPMENT_DELIVERY_DATE_FROM("sss.shipment.delivery.date.from", 1030460),
    SSS_SHIPMENT_DELIVERY_DATE_TO("sss.shipment.delivery.date.to", 1030461),
    SSS_SHIPMENT_DELIVERY_DATE("sss.shipment.delivery.date", 1030462),

    //==============================================================================================
    SSS_MANUFACTURE("sss.manufacture", 1031100),
    SSS_MANUFACTURE_NAME("sss.manufacture.name", 1031101),
    SSS_MANUFACTURE_CODE("sss.manufacture.code", 1031102),
    SSS_MANUFACTURE_STATUS("sss.manufacture.status", 1031103),
    SSS_MANUFACTURE_ID("sss.manufacture.id", 1031104),
    SSS_MANUFACTURE_LIST("sss.manufacture.list", 1031105),

    //==============================================================================================
    SSS_PRODUCT("sss.product", 1032201),
    SSS_PRODUCT_SKU("sss.product.sku", 1032202),
    SSS_PRODUCT_STATUS("sss.product.status", 1032203),
    SSS_PRODUCT_ID("sss.product.id", 1032204),
    SSS_PRODUCT_LIST("sss.product.list", 1032205),
    SSS_PRODUCT_NAME("sss.product.name", 1032206),
    SSS_PRODUCT_IMAGE("sss.product.image", 1032207),
    SSS_PRODUCT_DOCUMENT("sss.product.document", 1032208),
    SSS_PRODUCT_DESCRIPTION("sss.product.description", 1032209),
    SSS_PRODUCT_DESCRIPTION_4_REJECT("sss.product.description.4.reject", 1032210),

    //==============================================================================================
    SSS_PRODUCT_2_ATTR("sss.product2attr", 1033101),
    SSS_PRODUCT_2_ATTR_VALUE("sss.product2attr.value", 1033102),
    SSS_PRODUCT_2_ATTR_STATUS("sss.product2attr.status", 1033103),
    SSS_PRODUCT_2_ATTR_ID("sss.product2attr.id", 1033104),
    SSS_PRODUCT_2_ATTR_VALUE_MEASURE("sss.product2attr.value.measure", 1033105),
    //==============================================================================================
    SSS_INVOICE("sss.invoice", 1034100),
    SSS_INVOICE_NUMBER("sss.invoice.number", 1034101),
    SSS_INVOICE_KIND_ID("sss.invoice.kind", 1034102),
    SSS_INVOICE_STATUS("sss.invoice.status", 1034104),
    SSS_INVOICE_TOTAL_AMOUNT("sss.invoice.total.amount", 1034105),
    SSS_INVOICE_NOTE("sss.invoice.note", 1034106),
    SSS_INVOICE_DUE_DATE("sss.invoice.due.date", 1034107),
    SSS_INVOICE_ISSUE_DATE("sss.invoice.issue.date", 1035108),
    SSS_INVOICE_SUPPLIER_BANK_NAME("sss.invoice.supplier.bank.name", 1036109),
    SSS_INVOICE_SUPPLIER_EMAIL("sss.invoice.supplier.email", 1036110),
    SSS_INVOICE_RECEIVER_BANK_NAME("sss.invoice.receiver.bank.name", 1038111),
    SSS_INVOICE_RECEIVER_EMAIL("sss.invoice.receiver.email", 1039112),
    SSS_INVOICE_SUBTOTAL_AMOUNT("sss.invoice.subtootal.amount", 1039115),
    SSS_INVOICE_VAT_AMOUNT("sss.invoice.vat.amount", 1039116),
    SSS_INVOICE_SUPPLIER_BANK_ADDRESS("sss.invoice.supplier.bank.address", 1036120),
    SSS_INVOICE_RECEIVER_BANK_ADDRESS("sss.invoice.receiver.bank.address", 1036121),
    SSS_INVOICE_SUPPLIER_ACCOUNT("sss.invoice.supplier.account", 1036125),
    SSS_INVOICE_RECEIVER_ACCOUNT("sss.invoice.receiver.account", 1036126),
    SSS_INVOICE_SUPPLIER_SWIFT("sss.invoice.supplier.swift", 1036130),
    SSS_INVOICE_RECEIVER_SWIFT("sss.invoice.receiver.swift", 1036131),
    SSS_INVOICE_SUPPLIER_CURRENCY("sss.invoice.supplier.currency", 1036135),
    SSS_INVOICE_RECEIVER_CURRENCY("sss.invoice.receiver.currency", 1036136),
    SSS_INVOICE_SUPPLIER_BIC("sss.invoice.supplier.bic", 1036140),
    SSS_INVOICE_RECEIVER_BIC("sss.invoice.receiver.bic", 1036141),

    SSS_MANAGER_PRIVILEGE_CODE("sss.manager.privilege.code", 1040100),
    SSS_QP_PAGE_SIZE("sss.qp.page.size", 2010100),
    SSS_QP_PAGE_NUM("sss.qp.page.num", 2010101),

    //==============================================================================================
    SSS_WAREHOUSE("sss.warehouse", 211000),
    SSS_WAREHOUSE_TIME_TO_PREPARE("sss.warehouse.time.to.prepare", 211001),
    SSS_WAREHOUSE_NAME("sss.warehouse.name", 211002),
    SSS_WAREHOUSE_DATE("sss.warehouse.date", 211003),
    SSS_WAREHOUSE_COUNTRY("sss.warehouse.country", 211004),
    SSS_WAREHOUSE_CITY("sss.warehouse.city", 211005),
    SSS_WAREHOUSE_STREET("sss.warehouse.street", 211006),
    SSS_WAREHOUSE_INDEX("sss.warehouse.index", 211007),
    SSS_WAREHOUSE_HOUSE_NUMBER("sss.warehouse.house.number", 211008),
    SSS_WAREHOUSE_BUILDING("sss.warehouse.building", 211009),
    SSS_WAREHOUSE_PHONE("sss.warehouse.phone", 211010),
    SSS_WAREHOUSE_ADDRESS_FOR_RETURN("sss.warehouse.address.for.return", 211011),
    SSS_WAREHOUSE_INSTRUCTION_FOR_RETURN("sss.warehouse.instruction.for.return", 211012),
    SSS_WAREHOUSE_CODE("sss.warehouse.code", 211013),
    SSS_WAREHOUSE_STATUS("sss.warehouse.status", 211014),
    SSS_WAREHOUSE_ID("sss.warehouse.id", 211015),
    SSS_WAREHOUSE_LIST("sss.warehouse.list", 211016),
    SSS_WAREHOUSE_TRANSACTION("sss.warehouse.transaction", 211017),

    //==========================================================================
    SSS_REST("wh.rest", 221000),
    SSS_REST_DATE("wh.rest.date", 221001),
    SSS_REST_DATE_TIME("wh.rest.date.time", 221002),
    SSS_REST_TYPE("wh.rest.type", 221003),
    SSS_REST_CODE("wh.rest.code", 221010),
    SSS_PRODUCT_AMOUNT("wh.product.amount", 221020),
    SSS_TRANSACTION_TYPE_CODE("wh.transaction.type_code", 221030),
    SSS_TRANSACTION_CODE("wh.transaction.code", 221031),
    SSS_TRANSACTION_DATE("wh.transaction.date", 221040),
    SSS_TRANSACTION_AMOUNT("wh.transaction.amount", 221041),
    SSS_TRANSACTION("wh.transaction", 221050),
    //==========================================================================

    SSS_ACTIVATION_TOKEN("sss.activation.token", 220000),
    SSS_ACTIVATION_TOKEN_VALUE("sss.activation.token.value", 220010),
    SSS_ACTIVATION_TOKEN_ENTITY_TYPE("sss.activation.token.entity.type", 220011),
    SSS_ENTITY_TYPE("sss.entity.type", 220100),

    //==========================================================================
    SSS_REGISTRY_APPLICATION_EMAIL("sss.registry.application.email", 220200),
    SSS_REGISTRY_APPLICATION("sss.registry.application", 220201),
    SSS_REGISTRY_APPLICATION_FIRST_NAME("sss.registry.application.first.name", 220210),
    SSS_REGISTRY_APPLICATION_LAST_NAME("sss.registry.application.last.name", 220220),
    SSS_REGISTRY_APPLICATION_CODE("sss.registry.application.code", 220230),
    SSS_REGISTRY_APPLICATION_STATUS("sss.registry.application.status", 220240),

    //==========================================================================
    SSS_ABSTRACT_ATTRS_VALUES_VALUE("sss.abstract.attrs.values.value", 1100010),
    SSS_ABSTRACT_ATTRS_VALUES_CODE("sss.abstract.attrs.values.code", 1100011),
    SSS_ABSTRACT_ATTRS_VALUES_ASSIGNED("sss.abstract.attrs.valuese.assign", 1100012),
    SSS_ABSTRACT_ATTRS_VALUES_STATUS("sss.abstract.attrs.values.status", 1100013),

    //==========================================================================
    SSS_PARAM_GROUP_CODE("sss.param.group.code", 1200010),
    SSS_PARAM_GROUP_NAME("sss.param.group.name", 1200011),
    SSS_PARAM_GROUP("sss.param.group", 1200012),
    SSS_PARAM_GROUP_STATUS("sss.param.group.status", 1200013),
    SSS_PARAM_GROUP_PRIORITY("sss.param.group.priority", 1200014),
    SSS_PARAM_GROUP_LIST("sss.param.group.list", 1200015),

    //==========================================================================
    SSS_OFFER_STATUS("sss.offer.status", 1300010),
    SSS_OFFER_DATE("sss.offer.date", 1300011),

    //==========================================================================
    SSS_CART("sss.cart", 1400010),
    SSS_CART_ATTRIBUTE("sss.cart.attribute", 1400011),
    SSS_CART_STATUS("sss.cart.status", 1400020),

    //==========================================================================
    SSS_CART_ITEM("sss.cart.item", 1500010),
    SSS_CART_ITEM_READY_2_ORDER("sss.cart.item.ready.2.order", 1500011),

    //==========================================================================
    SSS_PAYMENT("sss.payment", 1700000),
    SSS_PAYMENT_NUM("sss.payment.num", 1700010),
    SSS_PAYMENT_STATUS("sss.payment.status", 1700011),
    SSS_PAYMENT_SUM("sss.payment.sum", 1700012),

    //==========================================================================
    SSS_APPLICATION_DISPUTE_CODE("sss.application.dispute.code", 1800010),
    SSS_APPLICATION_DISPUTE_STATUS("sss.application.dispute.status", 1800011),
    SSS_APPLICATION_DISPUTE_SHORT_STATUS("sss.application.dispute.short.status", 1800012),
    SSS_APPLICATION_DISPUTE_DESCRIPTION("sss.application.dispute.description", 1800013),
    SSS_APPLICATION_DISPUTE_IMAGES("sss.application.dispute.images", 1800014),
    SSS_APPLICATION_DISPUTE_TOPIC("sss.application.dispute.topic", 1800015),
    SSS_APPLICATION_DISPUTE_ANSWER("sss.application.dispute.answer", 1800016),
    SSS_APPLICATION_DISPUTE_EMAIL("sss.application.dispute.email", 1800017),

    //==========================================================================
    SSS_REVIEW_PRODUCT_COMMENT("sss.review.product.comment", 1900010),
    SSS_REVIEW_PRODUCT_RATING("sss.review.product.rating", 1900011),
    SSS_REVIEW_PRODUCT_IMAGES("sss.review.product.images", 1900012),
    SSS_REVIEW_PRODUCT_STATUS("sss.review.product.status", 1900013),
    SSS_REVIEW_PRODUCT_FIRST_NAME("sss.review.product.first.name", 1900014),
    SSS_REVIEW_PRODUCT_LAST_NAME("sss.review.product.last.name", 1900015),
    SSS_REVIEW_PRODUCT_CODE("sss.review.product.code", 1900016),
    SSS_REVIEW_PRODUCT_EXPIRED_TIME("sss.review.product.expired.time", 1900017),

    //==========================================================================
    SSS_FLD_CUSTOMER_LOGIN("sss.school.customer.old.login", 2000010),
    SSS_OLD_FLD_CUSTOMER_LOGIN("sss.school.customer.login", 2000011),
    SSS_SCHOOL_CUSTOMER_EMAIL("sss.school.customer.email", 2000012),
    SSS_SCHOOL_CUSTOMER_PASSWORD("sss.school.customer.password", 2000013),
    SSS_SCHOOL_CUSTOMER_CONFIRM_PASSWORD("sss.school.customer.confirm.password", 2000014),
    SSS_SCHOOL_CUSTOMER_LAST_NAME("sss.school.customer.last.name", 2000015),
    SSS_SCHOOL_CUSTOMER_FIRST_NAME("sss.school.customer.first.name", 2000016),
    SSS_SCHOOL_CUSTOMER_STATUS("sss.school.customer.status", 2000017),
    SSS_SCHOOL_CUSTOMER_PHONE("sss.school.customer.phone", 2000018),
    //===========================================================================
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_STATUS("sss.fin.manager.status", 2100011),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_LOGIN("sss.fin.manager.login", 2100012),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_OLD_MANAGER_LOGIN("sss.fin.old.manager.login", 2100013),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_PASSWORD("sss.fin.manager.password", 2100014),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_AVATAR_IMG("sss.fin.manager.avatar.img", 2100015),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_COUNTRY("sss.fin.manager.country", 2100016),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_REGION("sss.fin.manager.region", 2100017),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_PRIVILEGES("sss.fin.manager.privileges", 2100018),
    @Deprecated("Please use generic SSS_MANAGER_* fields")
    SSS_FIN_MANAGER_OLD_PASSWORD("sss.fin.manager.old.password", 2100019),
    //===========================================================================
    SSS_FIN_CUSTOMER_ACCOUNT("sss.fin.customer.account", 2200011),
    SSS_FIN_CUSTOMER_ACCOUNT_NAME("sss.fin.customer.account.name", 2200012),
    SSS_FIN_CUSTOMER_ACCOUNT_CODE("sss.fin.customer.account.code", 2200013),
    //===========================================================================
    SSS_REGION_COUNTRY_ISO("sss.region.country.iso", 2300011),
    //===========================================================================
    SSS_ACCOUNT_TRANSACTION_SUM("sss.account.transaction.sum", 2300012),
    SSS_ACCOUNT_TRANSACTION_KIND("sss.account.transaction.kind", 2300013),
    SSS_ACCOUNT_TRANSACTION_NOTE("sss.account.transaction.note", 2300014),
    SSS_ACCOUNT_TRANSACTION_STATUS("sss.account.transaction.status", 2300015),
    SSS_ACCOUNT_TRANSACTION_DATE("sss.account.transaction.date", 2300016),
    SSS_ACCOUNT_TRANSACTION_CODE("sss.account.transaction.num", 2300017),
    //===========================================================================
    SSS_CARD_TRANSACTION_SUM("sss.card.transaction.sum", 2400012),
    SSS_CARD_TRANSACTION_KIND("sss.card.transaction.kind", 2400013),
    SSS_CARD_TRANSACTION_NOTE("sss.card.transaction.note", 2400014),
    SSS_CARD_TRANSACTION_STATUS("sss.card.transaction.status", 2400015),
    SSS_CARD_TRANSACTION_DATE("sss.card.transaction.date", 2400016),
    SSS_CARD_TRANSACTION_CODE("sss.card.transaction.num", 2400017),
    //==========================================================================
    SSS_PI_ALG_ID("sss.product.import.algId", 1600010),
    //==========================================================================
    LMS_USER_ID("lms.user.id", 2500000),
    LMS_QUIZ_ID("lms.quiz.id", 2500001),
    LMS_MOODLE_PARAM_FOR_QUIZ("lms.moodle.param.4.quiz", 2500002),
    LMS_USER_QUIZ_IDS("lms.user.id.quiz.id", 2500003),
    LMS_JWT_MANAGER("lms.jwt.manager", 2500004),
    LMS_JWT_CUSTOMER("lms.jwt.customer", 2500005),
    LMS_MOODLE_REQUEST_CODE("lms.moodle.request.code", 2500006),
    LMS_FILTER_NAME("lms.moodle.filter.name", 2500007),
    LMS_FILTER_STATUS("lms.moodle.filter.status", 2500008),
    // Player
    //==================================================================================================================
    SSS_PLAYER("sss.player", 2600100),
    SSS_PLAYER_LOGIN("sss.player.login", 2600101),
    SSS_PLAYER_PASSWORD("sss.player.password", 2600102),
    SSS_PLAYER_OLD_PASSWORD("sss.player.password.old", 2600103),
    SSS_PLAYER_STATUS("sss.player.status", 2600104),
    SSS_PLAYER_LAST_NAME("sss.player.last.name", 2600105),
    SSS_PLAYER_MIDDLE_NAME("sss.player.middle.name", 2600106),
    SSS_PLAYER_FIRST_NAME("sss.player.first.name", 2600107),
    SSS_PLAYER_LIST("sss.player.list", 2600108),
    SSS_PLAYER_EMAIL("sss.player.email", 2600109),
    SSS_PLAYER_PHONE("sss.player.phone", 2600110),
    SSS_PLAYER_OLD_LOGIN("sss.player.login.old", 2600111),
    SSS_FEN("sss.fen.value", 2600112),
    SSS_FEN_DEPTH("sss.fen.depth", 2600113),
    SSS_FEN_TIMEOUT("sss.fen.timeout", 2600114),

    //==============================================================================
    S3_CORE_OUT_OF_SERVICE("core.out.of.service", 3100000),
    S3_CORE_OUT_OF_SERVICE_START_DATE("core.out.of.service.start.date", 3100001),
    S3_CORE_OUT_OF_SERVICE_FINISH_DATE("core.out.of.service.finish.date", 3100002),
    S3_CORE_OUT_OF_SERVICE_NOTE("core.out.of.service.note", 3100003),
    //==============================================================================
    S3_STRIPE_REGISTRY_D1("stripe.registry.d1", 3200000),
    S3_STRIPE_REGISTRY_D2("stripe.registry.d2", 3200001),

    // Player
    //==================================================================================================================
    SSS_INVITE("sss.invite", 5400000),
    SSS_INVITE_CODE("sss.invite.code", 5400010),
    SSS_INVITE_STATUS("sss.invite.status", 5400020),
    ;

    override fun getValue() = this.value

    override fun getCode() = this.code

}
