package org.dbs.ref.serv.enums

import org.dbs.application.core.service.funcs.TestFuncs
import org.dbs.application.core.service.funcs.TestFuncs.selectFrom
import org.dbs.consts.CountryIsoCode
import org.dbs.exception.UnknownEnumException

enum class CountryEnum(
    private val countryId: Int,
    private val countryIso: CountryIsoCode,
    private val countryIso3: CountryIsoCode,
    private val countryName: String
) {
    AF(4, "AF", "AFG", "Afghanistan"),
    AL(8, "AL", "ALB", "Albania"),
    DZ(12, "DZ", "DZA", "Algeria"),
    AS(16, "AS", "ASM", "American Samoa"),
    AD(20, "AD", "AND", "Andorra"),
    AO(24, "AO", "AGO", "Angola"),
    AI(660, "AI", "AIA", "Anguilla"),
    AQ(10, "AQ", "ATA", "Antarctica"),
    AG(28, "AG", "ATG", "Antigua and Barbuda"),
    AR(32, "AR", "ARG", "Argentina"),
    AM(51, "AM", "ARM", "Armenia"),
    AW(533, "AW", "ABW", "Aruba"),
    AU(36, "AU", "AUS", "Australia"),
    AT(40, "AT", "AUT", "Austria"),
    AZ(31, "AZ", "AZE", "Azerbaijan"),
    BS(44, "BS", "BHS", "Bahamas (the)"),
    BH(48, "BH", "BHR", "Bahrain"),
    BD(50, "BD", "BGD", "Bangladesh"),
    BB(52, "BB", "BRB", "Barbados"),
    BY(112, "BY", "BLR", "Belarus"),
    BE(56, "BE", "BEL", "Belgium"),
    BZ(84, "BZ", "BLZ", "Belize"),
    BJ(204, "BJ", "BEN", "Benin"),
    BM(60, "BM", "BMU", "Bermuda"),
    BT(64, "BT", "BTN", "Bhutan"),
    BO(68, "BO", "BOL", "Bolivia (Plurinational State of)"),
    BQ(535, "BQ", "BES", "Bonaire, Sint Eustatius and Saba"),
    BA(70, "BA", "BIH", "Bosnia and Herzegovina"),
    BW(72, "BW", "BWA", "Botswana"),
    BV(74, "BV", "BVT", "Bouvet Island"),
    BR(76, "BR", "BRA", "Brazil"),
    IO(86, "IO", "IOT", "British Indian Ocean Territory (the)"),
    BN(96, "BN", "BRN", "Brunei Darussalam"),
    BG(100, "BG", "BGR", "Bulgaria"),
    BF(854, "BF", "BFA", "Burkina Faso"),
    BI(108, "BI", "BDI", "Burundi"),
    CV(132, "CV", "CPV", "Cabo Verde"),
    KH(116, "KH", "KHM", "Cambodia"),
    CM(120, "CM", "CMR", "Cameroon"),
    CA(124, "CA", "CAN", "Canada"),
    KY(136, "KY", "CYM", "Cayman Islands (the)"),
    CF(140, "CF", "CAF", "Central African Republic (the)"),
    TD(148, "TD", "TCD", "Chad"),
    CL(152, "CL", "CHL", "Chile"),
    CN(156, "CN", "CHN", "China"),
    CX(162, "CX", "CXR", "Christmas Island"),
    CC(166, "CC", "CCK", "Cocos (Keeling) Islands (the)"),
    CO(170, "CO", "COL", "Colombia"),
    KM(174, "KM", "COM", "Comoros (the)"),
    CD(180, "CD", "COD", "Congo (the Democratic Republic of the)"),
    CG(178, "CG", "COG", "Congo (the)"),
    CK(184, "CK", "COK", "Cook Islands (the)"),
    CR(188, "CR", "CRI", "Costa Rica"),
    HR(191, "HR", "HRV", "Croatia"),
    CU(192, "CU", "CUB", "Cuba"),
    CW(531, "CW", "CUW", "Curaçao"),
    CY(196, "CY", "CYP", "Cyprus"),
    CZ(203, "CZ", "CZE", "Czechia"),
    CI(384, "CI", "CIV", "Côte d'Ivoire"),
    DK(208, "DK", "DNK", "Denmark"),
    DJ(262, "DJ", "DJI", "Djibouti"),
    DM(212, "DM", "DMA", "Dominica"),
    DO(214, "DO", "DOM", "Dominican Republic (the)"),
    EC(218, "EC", "ECU", "Ecuador"),
    EG(818, "EG", "EGY", "Egypt"),
    SV(222, "SV", "SLV", "El Salvador"),
    GQ(226, "GQ", "GNQ", "Equatorial Guinea"),
    ER(232, "ER", "ERI", "Eritrea"),
    EE(233, "EE", "EST", "Estonia"),
    SZ(748, "SZ", "SWZ", "Eswatini"),
    ET(231, "ET", "ETH", "Ethiopia"),
    FK(238, "FK", "FLK", "Falkland Islands (the) [Malvinas]"),
    FO(234, "FO", "FRO", "Faroe Islands (the)"),
    FJ(242, "FJ", "FJI", "Fiji"),
    FI(246, "FI", "FIN", "Finland"),
    FR(250, "FR", "FRA", "France"),
    GF(254, "GF", "GUF", "French Guiana"),
    PF(258, "PF", "PYF", "French Polynesia"),
    TF(260, "TF", "ATF", "French Southern Territories (the)"),
    GA(266, "GA", "GAB", "Gabon"),
    GM(270, "GM", "GMB", "Gambia (the)"),
    GE(268, "GE", "GEO", "Georgia"),
    DE(276, "DE", "DEU", "Germany"),
    GH(288, "GH", "GHA", "Ghana"),
    GI(292, "GI", "GIB", "Gibraltar"),
    GR(300, "GR", "GRC", "Greece"),
    GL(304, "GL", "GRL", "Greenland"),
    GD(308, "GD", "GRD", "Grenada"),
    GP(312, "GP", "GLP", "Guadeloupe"),
    GU(316, "GU", "GUM", "Guam"),
    GT(320, "GT", "GTM", "Guatemala"),
    GG(831, "GG", "GGY", "Guernsey"),
    GN(324, "GN", "GIN", "Guinea"),
    GW(624, "GW", "GNB", "Guinea-Bissau"),
    GY(328, "GY", "GUY", "Guyana"),
    HT(332, "HT", "HTI", "Haiti"),
    HM(334, "HM", "HMD", "Heard Island and McDonald Islands"),
    VA(336, "VA", "VAT", "Holy See (the)"),
    HN(340, "HN", "HND", "Honduras"),
    HK(344, "HK", "HKG", "Hong Kong"),
    HU(348, "HU", "HUN", "Hungary"),
    IS(352, "IS", "ISL", "Iceland"),
    IN(356, "IN", "IND", "India"),
    ID(360, "ID", "IDN", "Indonesia"),
    IR(364, "IR", "IRN", "Iran (Islamic Republic of)"),
    IQ(368, "IQ", "IRQ", "Iraq"),
    IE(372, "IE", "IRL", "Ireland"),
    IM(833, "IM", "IMN", "Isle of Man"),
    IL(376, "IL", "ISR", "Israel"),
    IT(380, "IT", "ITA", "Italy"),
    JM(388, "JM", "JAM", "Jamaica"),
    JP(392, "JP", "JPN", "Japan"),
    JE(832, "JE", "JEY", "Jersey"),
    JO(400, "JO", "JOR", "Jordan"),
    KZ(398, "KZ", "KAZ", "Kazakhstan"),
    KE(404, "KE", "KEN", "Kenya"),
    KI(296, "KI", "KIR", "Kiribati"),
    KP(408, "KP", "PRK", "Korea (the Democratic People's Republic of)"),
    KR(410, "KR", "KOR", "Korea (the Republic of)"),
    KW(414, "KW", "KWT", "Kuwait"),
    KG(417, "KG", "KGZ", "Kyrgyzstan"),
    LA(418, "LA", "LAO", "Lao People's Democratic Republic (the)"),
    LV(428, "LV", "LVA", "Latvia"),
    LB(422, "LB", "LBN", "Lebanon"),
    LS(426, "LS", "LSO", "Lesotho"),
    LR(430, "LR", "LBR", "Liberia"),
    LY(434, "LY", "LBY", "Libya"),
    LI(438, "LI", "LIE", "Liechtenstein"),
    LT(440, "LT", "LTU", "Lithuania"),
    LU(442, "LU", "LUX", "Luxembourg"),
    MO(446, "MO", "MAC", "Macao"),
    MG(450, "MG", "MDG", "Madagascar"),
    MW(454, "MW", "MWI", "Malawi"),
    MY(458, "MY", "MYS", "Malaysia"),
    MV(462, "MV", "MDV", "Maldives"),
    ML(466, "ML", "MLI", "Mali"),
    MT(470, "MT", "MLT", "Malta"),
    MH(584, "MH", "MHL", "Marshall Islands (the)"),
    MQ(474, "MQ", "MTQ", "Martinique"),
    MR(478, "MR", "MRT", "Mauritania"),
    MU(480, "MU", "MUS", "Mauritius"),
    YT(175, "YT", "MYT", "Mayotte"),
    MX(484, "MX", "MEX", "Mexico"),
    FM(583, "FM", "FSM", "Micronesia (Federated States of)"),
    MD(498, "MD", "MDA", "Moldova (the Republic of)"),
    MC(492, "MC", "MCO", "Monaco"),
    MN(496, "MN", "MNG", "Mongolia"),
    ME(499, "ME", "MNE", "Montenegro"),
    MS(500, "MS", "MSR", "Montserrat"),
    MA(504, "MA", "MAR", "Morocco"),
    MZ(508, "MZ", "MOZ", "Mozambique"),
    MM(104, "MM", "MMR", "Myanmar"),
    NA(516, "NA", "NAM", "Namibia"),
    NR(520, "NR", "NRU", "Nauru"),
    NP(524, "NP", "NPL", "Nepal"),
    NL(528, "NL", "NLD", "Netherlands (the)"),
    NC(540, "NC", "NCL", "New Caledonia"),
    NZ(554, "NZ", "NZL", "New Zealand"),
    NI(558, "NI", "NIC", "Nicaragua"),
    NE(562, "NE", "NER", "Niger (the)"),
    NG(566, "NG", "NGA", "Nigeria"),
    NU(570, "NU", "NIU", "Niue"),
    NF(574, "NF", "NFK", "Norfolk Island"),
    MP(580, "MP", "MNP", "Northern Mariana Islands (the)"),
    NO(578, "NO", "NOR", "Norway"),
    OM(512, "OM", "OMN", "Oman"),
    PK(586, "PK", "PAK", "Pakistan"),
    PW(585, "PW", "PLW", "Palau"),
    PS(275, "PS", "PSE", "Palestine, State of"),
    PA(591, "PA", "PAN", "Panama"),
    PG(598, "PG", "PNG", "Papua New Guinea"),
    PY(600, "PY", "PRY", "Paraguay"),
    PE(604, "PE", "PER", "Peru"),
    PH(608, "PH", "PHL", "Philippines (the)"),
    PN(612, "PN", "PCN", "Pitcairn"),
    PL(616, "PL", "POL", "Poland"),
    PT(620, "PT", "PRT", "Portugal"),
    PR(630, "PR", "PRI", "Puerto Rico"),
    QA(634, "QA", "QAT", "Qatar"),
    MK(807, "MK", "MKD", "Republic of North Macedonia"),
    RO(642, "RO", "ROU", "Romania"),
    RU(643, "RU", "RUS", "Russian Federation (the)"),
    RW(646, "RW", "RWA", "Rwanda"),
    RE(638, "RE", "REU", "Réunion"),
    BL(652, "BL", "BLM", "Saint Barthélemy"),
    SH(654, "SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha"),
    KN(659, "KN", "KNA", "Saint Kitts and Nevis"),
    LC(662, "LC", "LCA", "Saint Lucia"),
    MF(663, "MF", "MAF", "Saint Martin (French part)"),
    PM(666, "PM", "SPM", "Saint Pierre and Miquelon"),
    VC(670, "VC", "VCT", "Saint Vincent and the Grenadine"),
    WS(882, "WS", "WSM", "Samoa"),
    SM(674, "SM", "SMR", "San Marino"),
    ST(678, "ST", "STP", "Sao Tome and Principe"),
    SA(682, "SA", "SAU", "Saudi Arabia"),
    SN(686, "SN", "SEN", "Senegal"),
    RS(688, "RS", "SRB", "Serbia"),
    SC(690, "SC", "SYC", "Seychelles"),
    SL(694, "SL", "SLE", "Sierra Leone"),
    SG(702, "SG", "SGP", "Singapore"),
    SX(534, "SX", "SXM", "Sint Maarten (Dutch part)"),
    SK(703, "SK", "SVK", "Slovakia"),
    SI(705, "SI", "SVN", "Slovenia"),
    SB(90, "SB", "SLB", "Solomon Islands"),
    SO(706, "SO", "SOM", "Somalia"),
    ZA(710, "ZA", "ZAF", "South Africa"),
    GS(239, "GS", "SGS", "South Georgia and the South Sandwich Islands"),
    SS(728, "SS", "SSD", "South Sudan"),
    ES(724, "ES", "ESP", "Spain"),
    LK(144, "LK", "LKA", "Sri Lanka"),
    SD(729, "SD", "SDN", "Sudan (the)"),
    SR(740, "SR", "SUR", "Suriname"),
    SJ(744, "SJ", "SJM", "Svalbard and Jan Mayen"),
    SE(752, "SE", "SWE", "Sweden"),
    CH(756, "CH", "CHE", "Switzerland"),
    SY(760, "SY", "SYR", "Syrian Arab Republic"),
    TW(158, "TW", "TWN", "Taiwan (Province of China)"),
    TJ(762, "TJ", "TJK", "Tajikistan"),
    TZ(834, "TZ", "TZA", "Tanzania, United Republic of"),
    TH(764, "TH", "THA", "Thailand"),
    TL(626, "TL", "TLS", "Timor-Leste"),
    TG(768, "TG", "TGO", "Togo"),
    TK(772, "TK", "TKL", "Tokelau"),
    TO(776, "TO", "TON", "Tonga"),
    TT(780, "TT", "TTO", "Trinidad and Tobago"),
    TN(788, "TN", "TUN", "Tunisia"),
    TR(792, "TR", "TUR", "Turkey"),
    TM(795, "TM", "TKM", "Turkmenistan"),
    TC(796, "TC", "TCA", "Turks and Caicos Islands (the)"),
    TV(798, "TV", "TUV", "Tuvalu"),
    UG(800, "UG", "UGA", "Uganda"),
    UA(804, "UA", "UKR", "Ukraine"),
    AE(784, "AE", "ARE", "United Arab Emirates (the)"),
    GB(826, "GB", "GBR", "United Kingdom of Great Britain and Northern Ireland (the)"),
    UM(581, "UM", "UMI", "United States Minor Outlying Islands (the)"),
    US(840, "US", "USA", "United States of America (the)"),
    UY(858, "UY", "URY", "Uruguay"),
    UZ(860, "UZ", "UZB", "Uzbekistan"),
    VU(548, "VU", "VUT", "Vanuatu"),
    VE(862, "VE", "VEN", "Venezuela (Bolivarian Republic of)"),
    VN(704, "VN", "VNM", "Viet Nam"),
    VG(92, "VG", "VGB", "Virgin Islands (British)"),
    VI(850, "VI", "VIR", "Virgin Islands (U.S.)"),
    WF(876, "WF", "WLF", "Wallis and Futuna"),
    EH(732, "EH", "ESH", "Western Sahara"),
    YE(887, "YE", "YEM", "Yemen"),
    ZM(894, "ZM", "ZMB", "Zambia"),
    ZW(716, "ZW", "ZWE", "Zimbabwe"),
    AX(248, "AX", "ALA", "Åland Islands"),
    ;

    companion object {
        //==================================================================================================================
        //@get:Synchronized

        fun getEnum(countryId: Int): CountryEnum =
            entries.find { it.getCountryId() == countryId }
                ?: throw UnknownEnumException("Country not found ($countryId)")

        fun getEnum(countryIso: CountryIsoCode): CountryEnum =
            entries.find { it.getCountryIso() == countryIso }
                ?: throw UnknownEnumException("CountryIso not found ($countryIso)")


        fun isExistCountry(countryIso: String) = entries
            .any { it.getCountryIso() == countryIso }

        fun isExistEnum(id: Int) = entries.any { it.getCountryId() == id }

        val countryIsos by lazy { entries.map(CountryEnum::countryIso) }

        fun getRandomCountry() = selectFrom(countryIsos)
        
    }

    fun getCountryName() = this.countryName

    fun getCountryIso() = this.countryIso

    fun getCountryIso3() = this.countryIso3

    fun getCountryId() = this.countryId
}
