server {

    server_name  _;
    #listen  [::]:80;
    #    listen 443;
        listen [::]:443 ssl ipv6only=on;
    #    listen              443 ssl;
    #    server_name         www.example.com;
    #    keepalive_timeout   70;

        ssl_certificate     /etc/nginx/certs/k11dev.tech.crt;
        ssl_certificate_key /etc/nginx/certs/k11dev.tech.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

   location ~ ^/api/(login) {
        # белые поинты
        }


   location /api {
            auth_request /jwt/verify;  # Проверка авторизации
            # Ваши другие настройки для обработки запросов
            #...
        }

    location /jwt/verify {
        internal;

        proxy_set_header Host $host;
        proxy_set_header User-Agent nginx-verifyer;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header accept application/json;
        proxy_set_header Content-Type */*;

        proxy_pass https://dev01.k11dev.tech:1444/api/jwt/v1/verify;


       # Сохраняем заголовок Authorization в переменную
       set $auth_header $http_authorization;

       # Удаляем "Bearer " из заголовка Authorization
       set $token "";

       if ($auth_header ~* ^Bearer\s+(.*)$) {
         set $token $1;
       }

        if ($token = "") {
            return 400 '{"responseCode": "OC_ERROR", "message": "Unauthorized failed", "error": "Token verification failed"}';
        }

        # Передаем данные в формате JSON
        proxy_set_body '{"requestBodyDto": {"jwt": "$token"}, "version": "1.0"}';

        proxy_method POST;

        proxy_intercept_errors on;

        error_page 401 = @error401;  # Обработка ошибки 401

        }

#    location @error400 {
#        return 400 '{"responseCode": "OC_ERROR", "message": "Unauthorized failed", "error": "Token verification failed"}';
#    }

    location @error401 {
        return 401 '{"responseCode": "OC_ERROR", "message": "Unauthorized", "error": "Token verification failed"}';
    }
}
