/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    idea
}

dependencies {
    implementation(libs.reflection)
    implementation(libs.kotlin.stdlib.jdk8)
    compileOnly(libs.kotlin.reflect)
}

description = "application-core-api"
