version: '3.9'
services:
  mongodb_container:
    image: mongo:latest
    container_name: dev-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 321321
      MONGO_INITDB_DATABASE: dev_sss_pmt
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
