#!/bin/sh

proto_dir="build/proto"
flutter_project_location="front/chess24front"
core_project_location="../.."
generated="lib/src/core/grpc/generated"

start=$(date +%s.%N)

clear

rm -r $generated
rm -r $proto_dir
mkdir -p $proto_dir
mkdir -p $generated

cd $core_project_location

filename=""
find . -type f -name "*.proto" -not -path "*/build/*" -not -path "*/p-cm/*" | while read -r file; do
  filename=$(basename "$file");
  
  echo "copying  '$file' to $proto_dir"
  cp $file $flutter_project_location/$proto_dir/$filename

done

cd $flutter_project_location/$proto_dir

echo "[INFO] Compiling google files..."
  protoc \
    --proto_path=. \
    --dart_out=grpc:../../lib/src/core/grpc/generated \
    google/protobuf/any.proto \
    google/protobuf/wrappers.proto

echo "[INFO] Compiling..."
for filename in *; do
  echo "---compiling: ${filename}"

  protoc $filename \
    --proto_path=. \
    --dart_out=grpc:../../lib/src/core/grpc/generated \
    --experimental_allow_proto3_optional

done

cd ../..

rm -r $proto_dir

end=$(date +%s.%N)
runtime=$(echo "$end - $start" | bc -l)

echo "-------------------------------------"
echo "[INFO] Generated in $runtime seconds."
echo "-------------------------------------"
echo "Refreshing with pub get..."
flutter pub get
