package org.dbs.entity.core

import org.dbs.consts.ActionCodeId
import org.dbs.consts.ActionId
import org.dbs.consts.EntityId
import org.dbs.consts.EntityTypeId
import org.dbs.consts.OperDate
import org.dbs.consts.StringNote
import org.dbs.spring.ref.AbstractRefEntity
import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Column
import org.springframework.data.relational.core.mapping.Table
import java.time.LocalTime

// actionId is auto-generated by DB sequence: nextval('seq_action_id')
@Table("core_actions")
data class Action(
    @Id
    @Column("action_id")
    val actionId: ActionId? = null,

    @Column("entity_id")
    val entityId: EntityId,

    @Column("entity_type_id")
    val entityTypeId: EntityTypeId,

    @Column("user_id")
    val userId: EntityId,

    @Column("action_code")
    val actionCode: ActionCodeId,

    @Column("execute_date")
    val executeDate: OperDate,

    @Column("action_address")
    val actionAddress: String,

    @Column("err_msg")
    val errMsg: String?,

    @Column("action_duration")
    val actionDuration: LocalTime,

    @Column("notes")
    val notes: StringNote,
) : AbstractRefEntity<ActionId?>() {

    override fun getId() = actionId
}
